name: PatientRegister
environment: dev
requestLimit: 5
dev:
  database:
    host: 192.168.10.10
    port: 3306
    username: homestead
    password: secret
    db: patient
    charset: utf8
  redis:
    host: 127.0.0.1:6379
    username: ""
    password: ""
prod:
  database:
    host: 127.0.0.1
    port: 3306
    username: root
    password: root
    db: patient
    charset: utf8
log:
  http: true